- name: Install dependencies [Debian]
  become: true
  tags: always
  ansible.builtin.apt:
    name: "{{ validator_package_dependencies_debian }}"
    state: present
    update_cache: true

- name: Install docker prerequisites
  become: true
  tags: always
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
    state: present
    update_cache: true

- name: Import Docker GPG signing key
  become: true
  tags: always
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add Docker repository
  become: true
  tags: always
  ansible.builtin.apt_repository:
    repo: >
      deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
      https://download.docker.com/linux/{{ ansible_distribution | lower  }}
      {{ ansible_distribution_release }} stable
    state: present
    filename: docker
    update_cache: true

- name: Install Docker and its dependencies
  become: true
  tags: always
  ansible.builtin.apt:
    name: docker-ce
    state: present
    update_cache: true

- name: Restart Docker
  become: true
  tags: always
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: true

- name: Ensure group 'docker' exists
  become: true
  tags: always
  ansible.builtin.group:
    name: docker
    state: present

- name: Ensure current user is in group 'docker'
  become: true
  tags: always
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups:
      - docker
    append: true

- name: Uninstall rust
  tags: always
  ansible.builtin.shell: /home/ubuntu/.cargo/bin/rustup self uninstall -y
  changed_when: true
  failed_when: false

- name: Install rust
  tags: always
  ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  changed_when: true

- name: Install cargo make
  tags: always
  ansible.builtin.shell: /home/ubuntu/.cargo/bin/cargo install --force cargo-make
  changed_when: true

- name: Install foundryup
  tags: always
  ansible.builtin.shell: curl -L https://foundry.paradigm.xyz | bash
  changed_when: true

- name: Run foundryup
  tags: always
  ansible.builtin.shell: /home/ubuntu/.foundry/bin/foundryup
  changed_when: true

- name: Install nodejs gpg key
  tags: always
  become: true
  ansible.builtin.apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install nodejs repository
  tags: always
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ validator_nodejs_version }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: true

- name: Install nodejs
  tags: always
  become: true
  ansible.builtin.apt:
    name: nodejs
    state: present
