- name: Print file url to download
  tags: always
  ansible.builtin.debug:
    msg: "The following file will be downloaded: {{ validator_bin_repo_url }}/ipc-cli.linux-{{ validator__arch_map[ansible_architecture] }}"

- name: Remove previous downloaded version
  tags: always
  become: true
  ansible.builtin.file:
    path: "/tmp/ipc-cli.linux-{{ validator__arch_map[ansible_architecture] }}"
    state: absent

- name: Download repo archive
  tags: always
  become: true
  ansible.builtin.shell: aria2c -x5 "{{ validator_bin_repo_url }}/ipc-cli.linux-{{ validator__arch_map[ansible_architecture] }}" -d /tmp
  changed_when: true

- name: Remove previous repository installation
  tags: always
  become: true
  ansible.builtin.file:
    path: "{{ validator_ipc_repository_path }}"
    state: absent

- name: Ensure destination directory exists
  tags: always
  become: true
  ansible.builtin.file:
    path: "{{ validator_ipc_repository_path }}"
    state: directory
    mode: "0774"
    owner: ubuntu
    group: ubuntu

- name: Unarchive repo
  tags: always
  ansible.builtin.unarchive:
    src: "/tmp/ipc-cli.linux-{{ validator__arch_map[ansible_architecture] }}"
    dest: "{{ validator_ipc_repository_path }}"
    remote_src: true
