- name: Print file url to download
  tags: always
  ansible.builtin.debug:
    msg: "The following file will be downloaded: {{ validator_bin_repo_url }}/ipc-cli.linux-{{ validator__arch_map[ansible_architecture] }}"

- name: Download binaries archive
  tags: always
  become: true
  ansible.builtin.get_url:
    url: "{{ validator_bin_repo_url }}/ipc-cli.linux-{{ validator__arch_map[ansible_architecture] }}"
    dest: "/tmp/ipc-cli.linux-{{ validator__arch_map[ansible_architecture] }}"
    mode: "0755"
    owner: ubuntu
    group: ubuntu
    force: true

- name: Unarchive binaries
  tags: always
  ansible.builtin.unarchive:
    src: "/tmp/ipc-cli.linux-{{ validator__arch_map[ansible_architecture] }}"
    dest: "{{ validator_ipc_repository_path }}"
    remote_src: true
