- name: Copy templatized relayer service
  become: true
  tags: always
  ansible.builtin.template:
    src: relayer.service.j2
    dest: /etc/systemd/system/relayer.service
    mode: "0644"

- name: Restart relayer service
  become: true
  tags: always
  ansible.builtin.systemd_service:
    name: relayer
    state: restarted
    enabled: true
    daemon_reload: true
